name = "CodecLZO"
uuid = "cda889bb-a424-44da-af60-21a472ea483c"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CircularArrays = "1.3"
TranscodingStreams = "0.10"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
