name = "CodecLZO"
uuid = "cda889bb-a424-44da-af60-21a472ea483c"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LZO_jll = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
DataStructures = "0.18"
LZO_jll = "2.10"
TranscodingStreams = "0.10"
julia = "1.6"

[extras]
LZO_jll = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "Random", "LZO_jll"]
