name = "CodecLZO"
uuid = "cda889bb-a424-44da-af60-21a472ea483c"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
LibLZO = "32aa4ff1-cc5a-4ead-abec-09bb076ef871"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CircularArrays = "1.3"
LibLZO = "1.0"
TranscodingStreams = "0.10"
julia = "1.6"

[extras]
LibLZO = "32aa4ff1-cc5a-4ead-abec-09bb076ef871"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "LibLZO", "LazyArtifacts"]
